[package]
name = "regiusmark"
version = "0.0.1"
authors = ["Samuel Grenier <samrg472@gmail.com>"]
edition = "2018"

[lib]
name = "regiusmark"
path = "src/regiusmark/lib.rs"

[dependencies]
bs58 = "0.2.2"
bytes = "0.4.12"
crc32c = "0.4.0"
faster-hex = "0.3.1"
log = "0.4.7"
num-bigint = "0.2.2"
num-traits = "0.2.8"
parking_lot = "0.9.0"
rocksdb = "0.12.3"
sodiumoxide = { version = "0.2.2", default-features = false, features = ["std"] }
