[package]
name = "regiusmark-cli"
version = "0.2.0"
edition = "2018"
authors = ["Samuel Grenier <samrg472@gmail.com>"]
license = "MIT"
repository = "https://github.com/RegiusMark/regiusmark"
readme = "README.md"
homepage = "https://regiusmark.io"
description = """
Regius Mark core command-line interface with a wallet and other utilities.
"""

publish = false

[[bin]]
name = "regiusmark"
path = "src/main.rs"

[dependencies]
dirs = "2.0.2"
env_logger = "0.7.1"
faster-hex = "0.4.1"
regiusmark = { path = "../regiusmark" }
log = "0.4.8"
native-tls = "0.2.3"
rustyline = "5.0.4"
rocksdb = "0.12.4"
sodiumoxide = { version = "0.2.5", default-features = false, features = ["std"] }
url = "2.1.0"

[dependencies.clap]
version = "2.33.0"
default-features = false

[dependencies.tungstenite]
version = "0.9.1"
default-features = false
